version: '3.8'

services:
  python:
    build: images/Python
    init: true
    container_name: website
    env_file:
      - ./.env
    volumes:
      - ./images/Python/Project:/app
    restart: always
    depends_on:
      - db
    networks:
      - ft_network
    ports:
      - "8000:8000"

  db:
    build: images/DB
    init: true
    container_name: db
    env_file:
      - ./.env
    restart: always
    networks:
      - ft_network
    ports:
      - "5432:5432"

networks:
  ft_network:
        driver: bridge
